Fix issue when installing version 2.18.0
Because 'fsspec' is marked as optional using the pyAthena library fails because it is imported in `pyathena/pandas/__init__.py`

```
  File "/usr/local/lib/python3.8/dist-packages/pyathena/pandas/__init__.py", line 2, in <module>"
    import fsspec"
ModuleNotFoundError: No module named 'fsspec'
```